# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-31 00:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MessageApp', '0003_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='name',
            new_name='activate_key',
        ),
    ]
