# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-31 00:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MessageApp', '0004_auto_20160530_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='activate_key',
            field=models.CharField(max_length=64),
        ),
    ]
