# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-01 01:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MessageApp', '0005_auto_20160530_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='reset_key',
            field=models.CharField(default=None, max_length=64),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='activate_key',
            field=models.CharField(default=None, max_length=64),
        ),
    ]
