# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-01 01:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MessageApp', '0007_auto_20160531_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='activate_key',
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='reset_key',
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
    ]
