# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-01 01:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MessageApp', '0012_remove_userprofile_reset_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='reset_key',
            field=models.CharField(default='', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='activate_key',
            field=models.CharField(default='', max_length=64, null=True),
        ),
    ]
