# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-02 22:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('MessageApp', '0014_userprofile_activated_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='new_pass_created',
            field=models.DateField(default=datetime.datetime(2016, 6, 2, 22, 0, 54, 883281, tzinfo=utc)),
        ),
    ]
