# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-02 22:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MessageApp', '0015_userprofile_new_pass_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='new_pass_created',
            field=models.DateField(default=datetime.date(2016, 6, 2)),
        ),
    ]
