# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-04 22:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MessageApp', '0016_auto_20160602_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='new_pass_created',
            field=models.DateField(default=datetime.date(2016, 6, 4)),
        ),
    ]
