# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-04 22:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('MessageApp', '0017_auto_20160604_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='new_pass_created',
            field=models.DateField(default=datetime.datetime(2016, 6, 4, 22, 20, 26, 633310, tzinfo=utc)),
        ),
    ]
